name: Release
on:
  push:
    tags:
      - "v*"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: mstksg/setup-stack@v1
      - run: stack build
      - run: stack install --local-bin-path dist
      - uses: actions/upload-artifact@v1
        with:
          name: ${{ matrix.os }}
          path: dist
      - uses: softprops/action-gh-release@v1
        with:
          files: "dist/*"
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
